name: docs
channels:
  - conda-forge

  - defaults

dependencies:
  # Base depends
  - python
  - pip

  # Package dependencies
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - mdtraj
  - nglview
  - cython
  - nbsphinx
  - networkx
  - panel

  # Pip-only installs
  - pip:
    - tdqm
    - group-lasso
    - sphinx-copybutton  
    - furo

